### ISSUE TITLE
Use fzf instead of CtrlP

### ISSUE THREAD

**Issue by sbrahul** [dayarthvader/tools#2]
https://github.com/dayarthvader/tools/blob/7432e0f580ff936c8e04e8745f1780a8b2cbf43e/vim/.vimrc#L25

Use: https://github.com/junegunn/fzf.vim

**Comment by dayarthvader** [comment]
@sbrahul Thanks. FZF is really a whole package. Using it in the terminal right now. I will switch to fzf soon.

**Comment by dayarthvader** [comment]
@sbrahul Done.
